# Generated by Django 5.1.15 on 2025-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc_type', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('func_name', models.CharField(max_length=1024)),
                ('line_no', models.IntegerField()),
                ('line', models.TextField(blank=True, null=True)),
                ('stacks', models.JSONField(default=list)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(default=list)),
            ],
        ),
    ]
