# Generated by Django 5.1.15 on 2025-12-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_remove_exception_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'verbose_name': 'Logger', 'verbose_name_plural': 'Loggers'},
        ),
    ]
