# Generated by Django 5.1.15 on 2025-12-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
